version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
